#! /bin/sh
#

mkdir -p ../../../devel29/share/codeblocks/images/fortranproject> /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/fortranproject > /dev/null 2> /dev/null
cp ./images/fortranproject/*.* ../../../devel29/share/codeblocks/images/fortranproject/ > /dev/null 2> /dev/null
cp ./images/fortranproject/*.* ../../../output29/share/codeblocks/images/fortranproject/ > /dev/null 2> /dev/null
exit 0


